version: '3.8'

services:
  backend:
    build: ./backend/SSDjango
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/SSDjango:/code
    ports:
      - "8000:8000"
    env_file:
      - ./backend/SSDjango/.env

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
  
