# Generated by Django 3.2.4 on 2024-03-17 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teststudio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf',
            old_name='pdf_file',
            new_name='file',
        ),
    ]
