# Generated by Django 3.2.4 on 2024-03-21 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teststudio', '0005_auto_20240321_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='filtered',
            field=models.BooleanField(default=False),
        ),
    ]
