# Generated by Django 3.2.4 on 2024-03-28 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teststudio', '0006_token_filtered'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPTResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_json_response', models.TextField(db_column='json_response')),
                ('cost', models.FloatField()),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gpt_responses', to='teststudio.pdfpage')),
            ],
        ),
    ]
