# Generated by Django 3.2.4 on 2024-04-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teststudio', '0007_gptresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfpage',
            name='high_res_image',
            field=models.ImageField(blank=True, null=True, upload_to='high_res_images/'),
        ),
    ]
