# Generated by Django 5.0.4 on 2024-04-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfpage',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='token',
            name='token_confidence',
            field=models.FloatField(default=0.0),
        ),
    ]
