# Generated by Django 5.0.4 on 2024-04-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSAPP', '0005_remove_appkeys_django_secret_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compute_style_info', models.BooleanField(default=True)),
                ('enable_native_pdf_parsing', models.BooleanField(default=True)),
                ('enable_image_quality_scores', models.BooleanField(default=True)),
                ('enable_symbol', models.BooleanField(default=True)),
                ('location', models.CharField(default='us', max_length=32)),
                ('project_id', models.CharField(max_length=64)),
                ('processor_id', models.CharField(max_length=64)),
                ('processor_version', models.CharField(max_length=64)),
                ('mime_type', models.CharField(max_length=64)),
            ],
        ),
    ]
