# Generated by Django 5.0.4 on 2024-04-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSAPP', '0006_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='color_filter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='color_similarity_threshold',
            field=models.FloatField(default=0.6),
        ),
        migrations.AddField(
            model_name='settings',
            name='confidence_filter',
            field=models.FloatField(default=0.7),
        ),
        migrations.AddField(
            model_name='settings',
            name='font_size_filter',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='settings',
            name='handwritten_filter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='unicode_filter',
            field=models.BooleanField(default=True),
        ),
    ]
