# Generated by Django 5.0.4 on 2024-04-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SSAPP', '0007_settings_color_filter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='gpt_max_tokens',
            field=models.IntegerField(default=2048),
        ),
        migrations.AddField(
            model_name='settings',
            name='gpt_messages',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='settings',
            name='gpt_model',
            field=models.CharField(default='gpt-3.5-turbo', max_length=64),
        ),
    ]
